name: sentry
version: 3.0.1
description: >
  A crash reporting library for for Dart that sends crash reports to Sentry.io.
  This library supports Dart VM, and Flutter for mobile, web, and desktop.
homepage: https://github.com/flutter/sentry
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  meta: ^1.6.0
  stack_trace: ^1.10.0
  usage: ^4.0.2
  pedantic: ^1.11.1

dev_dependencies:
  args: ^2.1.1
  test: ^1.17.9
  yaml: ^3.1.0
  mockito: ^5.0.10
